🔀 Switch to using GitHub token for downloading artefacts (#56)
Signed-off-by: Jacob Woffenden <jacob.woffenden@justice.gov.uk>

diff --git a/setup-container-structure-test/action.yml b/setup-container-structure-test/action.yml
--- a/setup-container-structure-test/action.yml
+++ b/setup-container-structure-test/action.yml
@@ -3,6 +3,10 @@ name: Set Up Container Structure Test
 description: This action installs Google's [Container Structure Test](https://github.com/GoogleContainerTools/container-structure-test)
 
 inputs:
+  github-token:
+    description: GitHub token for authentication
+    required: false
+    default: ${{ github.token }}
   version:
     description: Version of Container Structure Test to install
     required: false
@@ -17,6 +21,8 @@ runs:
       id: install_container_structure_test
       shell: bash
       env:
+        GH_TOKEN: ${{ inputs.github-token }}
+        REPOSITORY: GoogleContainerTools/container-structure-test
         VERSION: ${{ inputs.version }}
       run: | # zizmor: ignore[github-env] we need to the binary to the path
         if [[ "$(uname --machine)" == "x86_64" ]]; then
@@ -29,15 +35,26 @@ runs:
         fi
 
         if [[ "${VERSION}" == "latest" ]]; then
-          export version="$(curl --silent https://api.github.com/repos/GoogleContainerTools/container-structure-test/releases/latest | jq -r '.tag_name')"
+          export version="$(gh release list --repo "${REPOSITORY}" --exclude-drafts --exclude-pre-releases --json "isLatest,tagName" | jq -r '.[] | select(.isLatest == true) | .tagName')"
         else
-          export version="${VERSION}"
+          if [[ "$(gh release list --repo "${REPOSITORY}" --exclude-pre-releases --json tagName | jq -r --arg tag "${VERSION}" '.[].tagName | select(. == $tag)')" != "${VERSION}" ]]; then
+            echo "Invalid version: ${VERSION}"
+            echo "Please check available versions on GitHub: https://github.com/${REPOSITORY}/releases"
+            echo "or use the command: gh release list --repo ${REPOSITORY} --exclude-pre-releases"
+            exit 1
+          else
+            export version="${VERSION}"
+          fi
         fi
 
         mkdir --parents "${GITHUB_WORKSPACE}/.container-structure-test"
 
-        curl --fail-with-body --location --silent "https://github.com/GoogleContainerTools/container-structure-test/releases/download/${version}/container-structure-test-linux-${architecture}" \
-          --output "${GITHUB_WORKSPACE}/.container-structure-test/container-structure-test"
+        gh release download \
+          --repo "${REPOSITORY}" \
+          "${version}" \
+          --pattern "container-structure-test-linux-${architecture}" \
+          --output "${GITHUB_WORKSPACE}/.container-structure-test/container-structure-test" \
+          --clobber
 
         chmod +x "${GITHUB_WORKSPACE}/.container-structure-test/container-structure-test"
 
diff --git a/setup-crane/action.yml b/setup-crane/action.yml
--- a/setup-crane/action.yml
+++ b/setup-crane/action.yml
@@ -3,6 +3,10 @@ name: Set Up crane
 description: This action installs Google's [crane](https://github.com/google/go-containerregistry/tree/main/cmd/crane)
 
 inputs:
+  github-token:
+    description: GitHub token for authentication
+    required: false
+    default: ${{ github.token }}
   version:
     description: Version of crane to install
     required: false
@@ -17,6 +21,8 @@ runs:
       id: install_crane
       shell: bash
       env:
+        GH_TOKEN: ${{ inputs.github-token }}
+        REPOSITORY: google/go-containerregistry
         VERSION: ${{ inputs.version }}
       run: | # zizmor: ignore[github-env] we need to the binary to the path
         if [[ "$(uname --machine)" == "x86_64" ]]; then
@@ -29,15 +35,26 @@ runs:
         fi
 
         if [[ "${VERSION}" == "latest" ]]; then
-          export version="$(curl --silent https://api.github.com/repos/google/go-containerregistry/releases/latest | jq -r '.tag_name')"
+          export version="$(gh release list --repo "${REPOSITORY}" --exclude-drafts --exclude-pre-releases --json "isLatest,tagName" | jq -r '.[] | select(.isLatest == true) | .tagName')"
         else
-          export version="${VERSION}"
+          if [[ "$(gh release list --repo "${REPOSITORY}" --exclude-pre-releases --json tagName | jq -r --arg tag "${VERSION}" '.[].tagName | select(. == $tag)')" != "${VERSION}" ]]; then
+            echo "Invalid version: ${VERSION}"
+            echo "Please check available versions on GitHub: https://github.com/${REPOSITORY}/releases"
+            echo "or use the command: gh release list --repo ${REPOSITORY} --exclude-pre-releases"
+            exit 1
+          else
+            export version="${VERSION}"
+          fi
         fi
 
         mkdir --parents "${GITHUB_WORKSPACE}/.crane"
 
-        curl --fail-with-body --location --silent "https://github.com/google/go-containerregistry/releases/download/${version}/go-containerregistry_Linux_${architecture}.tar.gz" \
-          --output "/tmp/go-containerregistry_Linux_${architecture}.tar.gz"
+        gh release download \
+          --repo "${REPOSITORY}" \
+          "${version}" \
+          --pattern "go-containerregistry_Linux_${architecture}.tar.gz" \
+          --output "/tmp/go-containerregistry_Linux_${architecture}.tar.gz" \
+          --clobber
 
         tar --extract --file "/tmp/go-containerregistry_Linux_${architecture}.tar.gz" --directory "${GITHUB_WORKSPACE}/.crane" crane
 
