✨ Add support for specifying Container Structure Test version and improve error handling for invalid versions
Signed-off-by: Jacob Woffenden <jacob.woffenden@justice.gov.uk>

diff --git a/setup-container-structure-test/action.yml b/setup-container-structure-test/action.yml
--- a/setup-container-structure-test/action.yml
+++ b/setup-container-structure-test/action.yml
@@ -22,6 +22,7 @@ runs:
       shell: bash
       env:
         GH_TOKEN: ${{ inputs.github_token }}
+        REPOSITORY: GoogleContainerTools/container-structure-test
         VERSION: ${{ inputs.version }}
       run: | # zizmor: ignore[github-env] we need to the binary to the path
         if [[ "$(uname --machine)" == "x86_64" ]]; then
@@ -34,15 +35,22 @@ runs:
         fi
 
         if [[ "${VERSION}" == "latest" ]]; then
-          export version="$(gh release list --repo GoogleContainerTools/container-structure-test --exclude-drafts --exclude-pre-releases --json "isLatest,tagName" | jq -r '.[] | select(.isLatest == true) | .tagName')"
+          export version="$(gh release list --repo "${REPOSITORY}" --exclude-drafts --exclude-pre-releases --json "isLatest,tagName" | jq -r '.[] | select(.isLatest == true) | .tagName')"
         else
-          export version="${VERSION}"
+          if [[ "$(gh release list --repo "${REPOSITORY}" --exclude-pre-releases --json tagName | jq -r --arg tag "${VERSION}" '.[].tagName | select(. == $tag)')" != "${VERSION}" ]]; then
+            echo "Invalid version: ${VERSION}"
+            echo "Please check available versions on GitHub: https://github.com/${REPOSITORY}/releases"
+            echo "or use the command: gh release list --repo ${REPOSITORY} --exclude-pre-releases"
+            exit 1
+          else
+            export version="${VERSION}"
+          fi
         fi
 
         mkdir --parents "${GITHUB_WORKSPACE}/.container-structure-test"
 
         gh release download \
-          --repo GoogleContainerTools/container-structure-test \
+          --repo "${REPOSITORY}" \
           "${version}" \
           --pattern "container-structure-test-linux-${architecture}" \
           --output "${GITHUB_WORKSPACE}/.container-structure-test/container-structure-test" \
